[package]
name = "genetic_algorithm_rust"
version = "0.1.0"
authors = ["Kyle Rassweiler <dev@kylerassweiler.ca>"]
edition = "2021"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"